# User Configuration for ${keyboard.name}

# ZMK Studio unlocked w/o the need of unlock keys 
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# Time in milliseconds before entering deep sleep (e.g., 900,000 ms = 15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 # 15 minutes
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000 # 10 minutes
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000 # 5 minutes

